export { default as TopDeals } from './TopDeals/TopDeals'
export { default as PopularProducts } from './PopularProducts/PopularProducts'
export { default as NewArrivals } from './NewArrivals/NewArrivals'
export { default as Item } from './ItemDetails/Item'
export { default as Cart } from './Cart/Cart'
export { default as Profile } from './Dashboard/Profile'
export { default as Orders } from './Dashboard/Orders'
export { default as Favourites } from './Dashboard/Favourites'